# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ChiaLing/Documents/ldfinal/final_project_tetris0/final_project_tetris0.srcs/sources_1/new/Basys3_Constraints.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/ChiaLing/Documents/ldfinal/final_project_tetris2/final_project_tetris2.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
